Threat shield
NethServer/nextsecurity pull request #24
Opened 2022-06-21 14:35 UTC by gsanchietti

Replace threat shield with:
- a NFT based solution for IP block lists
- a adblock based for DNS block lists

See also #22 

TODO:
- [x] support URL change (added documentation)
- [x] make sure to enable it after reboot
- [x] keep config file after removal
- [x] update NFT implementation to support multiple download URLs
- [x] threat shield DNS: try to add back the proxy bypass (see https://github.com/openwrt/packages/compare/master...NethServer:packages:adblock_bypass)

2022-06-22 08:06 UTC, gsanchietti commented
Ready for review @filippocarletti

2022-07-20 13:51 UTC, gsanchietti commented
See also nethesis/blacklists/pull/18

2022-07-22 09:17 UTC, filippocarletti requested changes
Fix package removal

2022-07-22 09:17 UTC, filippocarletti commented on packages/ns-threat_shield/Makefile
> +	/usr/sbin/ts
//usr/lib/opkg/info/ns-threat_shield.prerm: /usr/lib/opkg/info/ns-threat_shield.prerm-pkg: line 5: /usr/sbin/ts: not found
I guess it'd be `ts-ip`

2022-07-22 10:24 UTC, filippocarletti approved these changes

2022-07-25 12:07 UTC, gsanchietti commented
Bypass has been implemented as local patch to adblock.
See also #29

2022-07-25 12:08 UTC, merged