packages: add ns-phonehome
NethServer/nextsecurity pull request #79
Opened 2022-12-07 10:05 UTC by gsanchietti

Send statistical data to remote server

2022-12-07 14:17 UTC, filippocarletti requested changes

2022-12-07 14:17 UTC, filippocarletti commented on packages/ns-phonehome/README.md
> +uci set phonehome.config.enabled=1
```suggestion
uci set phonehome.config.enabled=0
```

2022-12-07 14:17 UTC, filippocarletti commented on packages/ns-phonehome/files/20_ns-phonehome
> +crontab -l | grep -q '/usr/sbin/send-heartbeat' || echo '10 4 * * * sleep $(( RANDOM % 1800 )); /usr/sbin/send-phonehome' >> /etc/crontabs/root
```suggestion
crontab -l | grep -q '/usr/sbin/send-phonehome' || echo '10 4 * * * sleep $(( RANDOM % 1800 )); /usr/sbin/send-phonehome' >> /etc/crontabs/root
```

2022-12-07 15:57 UTC, merged

2022-12-09 07:51 UTC, DavidePrincipi commented on packages/ns-phonehome/files/phonehome
> +print(json.dumps(data))
More IOStream-friendly

    json.dump(data, fp=sys.stdout)